<template>
  <main class="page-shell"><Sidebar/><section class="content"><RouterLink to="/dashboard">← Назад</RouterLink><h1>Создај Secret Santa настан</h1>
    <form class="card form-card" @submit.prevent="submit"><label>Име на настан</label><input v-model.trim="form.name" class="form-input" required placeholder="Secret Santa FINKI 2026"/><label>Опис</label><textarea v-model.trim="form.description" class="form-input" rows="4" placeholder="Краток опис на настанот"></textarea><div class="two"><div><label>Буџет (ден.)</label><input v-model.number="form.budget" class="form-input" type="number" min="0" required/></div><div><label>Датум на извлекување</label><input v-model="form.drawDate" class="form-input" type="date" required/></div></div><label>Рок за приклучување</label><input v-model="form.joinDeadline" class="form-input" type="date"/><p v-if="error" class="error">{{error}}</p><button class="btn btn-red" :disabled="loading">{{loading?'Се креира...':'Создај настан'}}</button></form>
    <section v-if="created" class="card success"><h2>🎉 Настанот е креиран!</h2><p>Код за приклучување</p><div class="join-code">{{created.joinCode}}</div><button class="btn btn-outline" @click="copyCode">📋 Копирај код</button><RouterLink class="btn btn-primary" :to="`/groups/${created.id}`">Отвори настан</RouterLink></section>
  </section></main>
</template>
<script setup>
import { reactive, ref } from 'vue'; import Sidebar from '../components/Sidebar.vue'; import { useAuthStore } from '../stores/authStore'; import { createEvent } from '../services/eventService';
const authStore=useAuthStore(), loading=ref(false), error=ref(''), created=ref(null); const form=reactive({name:'',description:'',budget:1000,drawDate:'',joinDeadline:''})
async function submit(){error.value='';loading.value=true;try{created.value=await createEvent({uid:authStore.user.uid,name:authStore.profile?.name||authStore.user.displayName||'Корисник',email:authStore.user.email},form)}catch(e){error.value=e.message||'Не успеа креирањето на настанот.'}finally{loading.value=false}}
async function copyCode(){if(created.value) await navigator.clipboard.writeText(created.value.joinCode)}
</script>
<style scoped>h1{color:var(--dark-green)}.form-card{max-width:760px;padding:28px;display:grid;gap:14px;margin-top:22px}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{font-weight:700;font-size:14px}textarea{resize:vertical}.error{color:var(--red);font-weight:700}.success{max-width:760px;padding:28px;margin-top:24px}.join-code{font-size:34px;letter-spacing:7px;font-weight:900;background:white;border:1px dashed var(--border);padding:18px;border-radius:14px;margin:12px 0 18px}.success .btn{display:inline-block;margin-right:10px}@media(max-width:650px){.two{grid-template-columns:1fr}}</style>
