<template><main class="page-shell"><Sidebar/><section class="content"><div class="top"><div><h1>Здраво, {{ firstName }}! 👋</h1><p>Еве преглед на вашите Secret Santa настани.</p></div><RouterLink to="/events/create" class="btn btn-red">+ Создај настан</RouterLink></div>
  <section class="card join"><h2>🔑 Приклучи се на настан</h2><div class="join-row"><input v-model.trim="joinCode" class="form-input" maxlength="6" placeholder="Внеси 6-знаковен код"/><button class="btn btn-primary" @click="join" :disabled="joining">Приклучи се</button></div><p v-if="joinError" class="error">{{joinError}}</p></section>
  <h2>Мои настани</h2><p v-if="loading">Се вчитуваат настаните...</p><div v-else-if="events.length" class="events"><EventCard v-for="event in events" :key="event.id" :id="event.id" icon="🎁" :title="event.name" :members="event.members" :status="statusLabel(event.status)"/></div><section v-else class="card empty">Сè уште немате настани. Создајте нов или приклучете се со код.</section>
  <section class="card quick"><h2>Брзи дејства</h2><div class="quick-grid"><RouterLink to="/events/create">➕ Создај настан</RouterLink><RouterLink to="/wishlist">❤️ Мој Wishlist</RouterLink><RouterLink to="/profile">👤 Мој профил</RouterLink></div></section>
</section></main></template>
<script setup>
import { computed,onMounted,ref } from 'vue'; import { useRouter } from 'vue-router'; import Sidebar from '../components/Sidebar.vue'; import EventCard from '../components/EventCard.vue'; import { useAuthStore } from '../stores/authStore'; import { getMyEvents,joinEventByCode } from '../services/eventService';
const authStore=useAuthStore(),router=useRouter(),events=ref([]),loading=ref(true),joinCode=ref(''),joinError=ref(''),joining=ref(false); const firstName=computed(()=>authStore.profile?.name?.split(' ')[0]||'')
function statusLabel(s){return s==='drawn'?'Извлечен':s==='completed'?'Завршен':'Активен'}
async function load(){loading.value=true;try{events.value=await getMyEvents(authStore.user.uid)}finally{loading.value=false}}
async function join(){joinError.value='';if(!joinCode.value)return;joining.value=true;try{const id=await joinEventByCode({uid:authStore.user.uid,name:authStore.profile?.name||'Корисник',email:authStore.user.email},joinCode.value);router.push(`/groups/${id}`)}catch(e){joinError.value=e.message}finally{joining.value=false}}
onMounted(load)
</script>
<style scoped>.top{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:24px}h1{color:var(--dark-green);margin:0}p{color:var(--muted)}.join{padding:22px;margin-bottom:28px}.join h2{margin-top:0}.join-row{display:flex;gap:12px;max-width:620px}.events{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin-bottom:28px}.quick{padding:26px}.quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.quick-grid a{border:1px solid var(--border);border-radius:18px;padding:28px;text-align:center;background:white;font-weight:700}.empty{padding:28px;margin-bottom:28px}.error{color:var(--red);font-weight:700}@media(max-width:950px){.events,.quick-grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}@media(max-width:600px){.join-row{flex-direction:column}}</style>
