<template><main class="page-shell"><Sidebar/><section class="content"><h1>Мој профил</h1><section class="card profile"><div class="avatar">👤</div><div class="profile-data"><label>Име и презиме</label><h2>{{profile?.name||'—'}}</h2><label>Е-пошта</label><p>{{authStore.user?.email}}</p><label>Оддел</label><p>{{profile?.department||'Не е внесен'}}</p><button class="btn btn-outline" @click="editing=!editing">✏️ Уреди профил</button></div></section>
  <form v-if="editing" class="card edit" @submit.prevent="save"><h2>Уреди профил</h2><label>Име и презиме</label><input v-model.trim="form.name" class="form-input" required/><label>Оддел</label><input v-model.trim="form.department" class="form-input"/><button class="btn btn-primary">Зачувај</button></form>
  <h2>Статистика</h2><div class="stats"><div class="card">🎁<b>{{eventCount}}</b><span>Настани</span></div><div class="card">🎯<b>{{drawnCount}}</b><span>Извлекувања</span></div><div class="card">❤️<b>{{wishCount}}</b><span>Желби</span></div></div>
</section></main></template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue'; import Sidebar from '../components/Sidebar.vue'; import { useAuthStore } from '../stores/authStore'; import { updateUserProfile } from '../services/userService'; import { getMyEvents } from '../services/eventService'; import { getWishlist } from '../services/wishlistService';
const authStore=useAuthStore(),editing=ref(false),events=ref([]),wishCount=ref(0),form=reactive({name:'',department:''}); const profile=computed(()=>authStore.profile); const eventCount=computed(()=>events.value.length); const drawnCount=computed(()=>events.value.filter(e=>e.status==='drawn').length)
onMounted(async()=>{Object.assign(form,{name:profile.value?.name||'',department:profile.value?.department||''});events.value=await getMyEvents(authStore.user.uid);wishCount.value=(await getWishlist(authStore.user.uid)).length})
async function save(){await updateUserProfile(authStore.user.uid,form);await authStore.hydrate(authStore.user);editing.value=false}
</script>
<style scoped>h1{color:var(--dark-green)}.profile{padding:32px;display:flex;gap:36px;align-items:center;max-width:850px}.avatar{width:140px;height:140px;display:grid;place-items:center;border-radius:50%;background:#f2e7db;font-size:80px}.profile-data{flex:1}label{color:var(--muted);font-size:14px}.edit{max-width:850px;padding:26px;margin:22px 0;display:grid;gap:12px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;max-width:850px}.stats .card{padding:30px;display:grid;place-items:center;font-size:34px}.stats b{font-size:30px;margin-top:8px}.stats span{font-size:14px;color:var(--muted)}@media(max-width:800px){.profile{flex-direction:column;align-items:flex-start}.stats{grid-template-columns:1fr}}</style>
